### ISSUE TITLE
Increase size of section letter column

### ISSUE THREAD

**Issue by jonatanschroeder** [kukuminer/ta-app#125]
If we have a string like "A/B/C".

**Comment by kukuminer** [comment]
I'll add a migration to set it to varchar(10). Do you think that will be enough?

**Comment by jonatanschroeder** [comment]
That should be fine.

**Comment by kukuminer** [comment]
Looks like PSQL doesn't allow migrations if there is a view that depends on the data. I could make the migration try to drop all views and then rebuild them, unless we don't use any views on the live server. I use some locally, which is why I ran into this issue.

**Comment by jonatanschroeder** [comment]
The live server has two views (sectionview and applicationview), but I don't see any reference to these in the code. I also don't use any view in my handling of the data, feel free to drop them in the migration.

**Comment by kukuminer** [comment]
This is in main, it was deployed with the bug fix to #127
