### ISSUE TITLE
Show constant warning to applicant if availability is zero

### ISSUE THREAD

**Issue by jonatanschroeder** [kukuminer/ta-app#129]
We have a few applicants that have set their availability to zero by mistake. I want to make sure that, if they do that, they understand what this means. The warning should be shown on the top in a fixed position. Also, the "Submit" button could be changed to something like "Confirm unavailability", with a tooltip that mentions an availability of zero.

**Comment by jonatanschroeder** [comment]
Please change the availability field to be a select, with the options:

* 0 (not available)
* 1 quarter load (0.25 load, 33.75 hours)
* 2 quarter loads (0.5 load, 67.5 hours)
* 3 quarter loads (0.75 load, 101.25 hours)
* 4 quarter loads (full load, 135 hours)

**Comment by kukuminer** [comment]
Completed. Let me know if you want any kind of additional helper text like there was before
![image](https://github.com/user-attachments/assets/ad1ea62f-7ff1-4c37-bfe9-1673bb7e85e5)

![image](https://github.com/user-attachments/assets/a12b696e-fc92-4799-a2a1-e99e87422bdd)

![image](https://github.com/user-attachments/assets/dddc840d-9b84-478a-a221-c03f76fcb7c9)

**Comment by kukuminer** [comment]
resolved by #151
