### ISSUE TITLE
Add campus information to sessions

### ISSUE THREAD

**Issue by jonatanschroeder** [kukuminer/ta-app#130]
With Markham starting soon, we need to identify what applicant preferences are for which campus they are willing to work at. This could be done by adding a table on campus, and then assign a section to a campus. The application table should also include the campus. For applicants, then, the courses should be broken down by campus (i.e., list all courses with sections at Keele, then list all courses with sections at Markham).

**Comment by kukuminer** [comment]
- [ ] add campus column to sections
- [ ] add enum for campuses (Keele, Glendon, Markham) [ordered]
- [ ] add migration
- [ ] Add header to tables per campus
- [ ] split applicant tables by campus
- [ ] add campus column to application as a unique constraint (applicant, course, term) -> (applicant, course, term, campus)

**Comment by kukuminer** [comment]
@jonatanschroeder should I make a new db migration for each change, or can I make all the changes in one file? ie. Can I put the following all in one new migration, or should I make a separate file for each?
CREATE ENUM...
ALTER TABLE section ADD campus...
ALTER TABLE applicant ADD campus...

**Comment by kukuminer** [comment]
Thanks. New question about adding columns: if I set a column as required (ie. NOT NULL), it must have a default value. Is it safe to put Keele as the default for the application table? Should I put Keele as the default for the section table too?

**Comment by jonatanschroeder** [comment]
Keele is fine. I can update them manually on deploy.
