### ISSUE TITLE
Add field for in person availability to term application 

### ISSUE THREAD

**Issue by jonatanschroeder** [kukuminer/ta-app#155]
Radio after the availability field, before the courses. Two options:
- I am available for in person activities (labs, tutorials, invigilation, etc.)
- I am only available for online activities (grading, Zoom office hours, student forums, etc.)

Add a note below it:
> Note that some online only availability may reduce the number of positions you may qualify for, and may impact the number of hours you may be assigned to.

**Comment by kukuminer** [comment]
Should this option be displayed to instructors in any way?

**Comment by jonatanschroeder** [comment]
Yes, a column listing "Online only" or "In person", titled "Availability".
