### ISSUE TITLE
Courses are listed duplicated in student application

### ISSUE THREAD

**Issue by jonatanschroeder** [kukuminer/ta-app#159]
Courses with more than one section are listed duplicated in the preference system.

**Comment by jonatanschroeder** [comment]
Workaround in production: changed this query to `SELECT DISTINCT`.
https://github.com/kukuminer/ta-app/blob/7a28bb86c72c9f1b1dafa21ea7b3b0aef29b572e/server/api/applicant.js#L190

**Comment by kukuminer** [comment]
redo query

**Comment by kukuminer** [comment]
select distinct + query redone. turns out distinct is a pretty elegant way of solving this
