### ISSUE TITLE
Datagrid limits the number of applicants listed per page

### ISSUE THREAD

**Issue by jonatanschroeder** [kukuminer/ta-app#163]
The datagrid page with applicants for a section is currently limiting the number of applicants being listed. I believe this is a [limitation in the free version](https://mui.com/x/react-data-grid/pagination/#community-plan). Please either enable pagination controls (plus a search element) or work on a different alternative.

**Comment by kukuminer** [comment]
enable pagination view
try to enable always display on 3 dot instead of hover only

**Comment by kukuminer** [comment]
enabled footer (pagination scrolling)
added custom toolbar (creates a searchbar and complex filter box)

**Comment by jonatanschroeder** [comment]
I assume a PR is coming? Can you include screenshots?
