### ISSUE TITLE
Allow instructor to see notes of other instructors

### ISSUE THREAD

**Issue by kukuminer** [kukuminer/ta-app#41]
For keeping track of notes, replace assignment table in DB with one with PK (instructor, applicant, course).

**Comment by kukuminer** [comment]
For when a prof is teaching more than one section of a particular course

display note for current instructor

button to click to reveal notes and preference from other instructors in the format:

**Michael Brown** - Requested/Critical/etc:
"Note goes here"

**Jonatan Schroeder** - No preference:
"Jonatan's note here"

**Comment by jonatanschroeder** [comment]
This will be changed so that the backend does not need to be modified. In essence, the section will be populated with a combined "pseudo-section" of all sections that an instructor is teaching. So the change will be done by admin in the way that sections are populated, not in the display itself.

The PR remains open only for the notes part: one instructor should be able to see the notes of other instructors.

**Comment by kukuminer** [comment]
@jonatanschroeder I've noticed an issue: each section can only have 1 prof assigned to it. So your workaround might not work as well as you would hope. I think we need some kind of DB change since `(course, letter, term)` is a unique constraint for the section table. I could remove `profid` from the section table and move it to its own table with `sectionId, profId` as the keys. I think this is probably the cleanest way to allow your workaround and the solution of seeing other professor's notes. Alternatively, we could just get rid of the unique constraint, but that would result in duplicate data since the only difference between rows would be the `profid` column. 

schema for section table right now:
```
ta_db=# \d section
                                   Table "public.section"
 Column |         Type         | Collation | Nullable |               Default
--------+----------------------+-----------+----------+-------------------------------------
 id     | integer              |           | not null | nextval('section_id_seq'::regclass)
 course | integer              |           | not null |
 letter | character varying(4) |           | not null |
 term   | integer              |           | not null |
 profid | integer              |           | not null |
Indexes:
    "section_pkey" PRIMARY KEY, btree (id)
    "section_course_letter_term_key" UNIQUE CONSTRAINT, btree (course, letter, term)
Foreign-key constraints:
    "section_course_fkey" FOREIGN KEY (course) REFERENCES course(id) ON UPDATE CASCADE ON DELETE CASCADE
    "section_profid_fkey" FOREIGN KEY (profid) REFERENCES instructor(id) ON UPDATE CASCADE ON DELETE CASCADE
    "section_term_fkey" FOREIGN KEY (term) REFERENCES term(id) ON UPDATE CASCADE ON DELETE CASCADE
Referenced by:
    TABLE "assignment" CONSTRAINT "assignment_section_fkey" FOREIGN KEY (section) REFERENCES section(id) ON UPDATE CASCADE ON DELETE CASCADE
```

**Comment by jonatanschroeder** [comment]
I don't think it's necessary. If I can create a pseudo-section that combines multiple sections of the same instructors into one, I can also create pseudo-sections that split them. So if I have 4 sections:

A -> Jonatan and Marcus
B -> Jonatan
C -> Suprakash
D -> Suprakash

I could have 3 pseudo-sections:

A1/B -> Jonatan
A2 -> Marcus
C/D -> Suprakash

So as long as the letter supports a longer width (see #125), it should be fine.
