### ISSUE TITLE
Remove unique restriction on student number

### ISSUE THREAD

**Issue by jonatanschroeder** [kukuminer/ta-app#56]
We have had a few issues with students that had more than one PPY starting an application in one account, then moving to another. While this is not ideal, there are good reasons for it (e.g., one PPY was a student account, which became deactivated due to graduation after they started the application). The problem was that they used the same student number (which they should), which caused a DB issue. This issue did not block the application from proceeding, but meant that none of the changes were saved in the DB. I removed the unique constraint from the DB in production to avoid this problem.

There can still be some kind of check to avoid duplication, but it should not be a DB constraint. In particular, if there is a duplicate student number, there should be a warning instead, but the process should be allowed to proceed. Same for the employee ID.

**Comment by kukuminer** [comment]
solved by migrations branch
