### ISSUE TITLE
Add clarification that the page is not an application

### ISSUE THREAD

**Issue by jonatanschroeder** [kukuminer/ta-app#62]
There have been a few applicants that got confused about the page, so we should make it clear that this page is not the application, it's just a set of preferences. This is particularly important for unit 2 applicants. Here's a suggested set of changes:

* Remove any reference to "apply", instead use terms like "submit preferences" or similar.
* Change titles to ensure the page lists this as a "Supplementary preference form", not an "Application".
* Include, in the preference form, a radio set with options:
  * I have submitted an application at the CUPE jobs web page (https://cupejobs.uit.yorku.ca/)
  * ~~I don't have an employee ID and so~~ I am unable to submit an application at the CUPE jobs web page
* If the latter is provided, include ~~the equivalent fields provided in an email application (a CV attachment plus either the appendix F form as PDF or the corresponding values as a form).~~ a note asking them to email [vinguyen@yorku.ca](mailto:vinguyen@yorku.ca) attaching their CV and appendix F (https://3903.cupe.ca/files/2014/06/blanket-app-unit-2-revised-Oct-2016_FINAL-3.pdf).

**Comment by jonatanschroeder** [comment]
The latter can be, for now, a note asking them to email vinguyen@yorku.ca attaching the CV and appendix F (https://3903.cupe.ca/files/2014/06/blanket-app-unit-2-revised-Oct-2016_FINAL-3.pdf).

**Comment by kukuminer** [comment]
For the 3rd bullet, its not a server-side change. Just a radio button question to bring their attention to the fact that there are other steps they need to take. If they answer that they have not completed that step, show an alert with instructions on how to do it.
Radio question is not mandatory and answer is not saved.

**Comment by kukuminer** [comment]
- [ ] rename "apply" -> something else
- [ ] change titles
- [ ] add radio button
- [ ] add help labels

**Comment by jonatanschroeder** [comment]
Application form:
* Unit 1: https://3903.cupe.ca/wp-content/blogs.dir/266/2014/06/blanket-app-unit-1-revised-Oct-2016_FINAL-3.pdf
* Unit 2: https://3903.cupe.ca/wp-content/blogs.dir/266/2014/06/blanket-app-unit-2-revised-Oct-2016_FINAL-3.pdf

**Comment by kukuminer** [comment]
![image](https://github.com/user-attachments/assets/b9aab6d1-380c-4f1b-81db-744ddfa95005)
@jonatanschroeder any ideas how to phrase this? withdraw preferences doesn't have the implication I would like- if you withdraw, your application won't show up for professors at all, so it feels more impactful than just "not submitting preferences".

**Comment by jonatanschroeder** [comment]
If you unsubmit, your preferences will no longer be considered.

**Comment by kukuminer** [comment]
@jonatanschroeder heres the updated stuff. Let me know if anything is missing or if you want to re-phrase anything. I've pushed the changes to the form-changes branch. There's another screenshot on the other issue with the other alert also.
The info alert only appears if the user selects the 2nd radio option. 

![image](https://github.com/user-attachments/assets/661c2b29-4057-4bc6-87ab-a9b86c05969e)

**Comment by kukuminer** [comment]
The unit of the user is not something that is fetched on this page. I could make it, though it would be a bit more complicated. I've changed the wording and added both unit links. Should I specify that unit 1 = graduate students and unit 2 = anyone else? I think a little reminder might serve useful to the user.

**Comment by jonatanschroeder** [comment]
> Should I specify that unit 1 = graduate students and unit 2 = anyone else? I think a little reminder might serve useful to the user.

Sure, wouldn't hurt.

**Comment by kukuminer** [comment]
resolved by #151
