### ISSUE TITLE
Push termapplications forward by default

### ISSUE THREAD

**Issue by kukuminer** [kukuminer/ta-app#66]
Whenever a new term is created, students most recent termapplications should be copied to the new term. 
Maybe only copy from previous term if it exists?

**Comment by jonatanschroeder** [comment]
I think it should copy from whatever previous term had a particular course.

**Comment by kukuminer** [comment]
Copy from previous term if it exists

**Comment by kukuminer** [comment]
term wizard branch allows admin to create new terms and modify visibility of existing terms

**Comment by kukuminer** [comment]
@jonatanschroeder is it important to update the DB with the "pulled forward" values? At the moment, I have modified the endpoint to simply return the student's latest preferences for each course if a preference does not exist in the current term. However, the backend is not actually updated with the "latest" preference unless the student makes a change (the same way it's not updated if the student leaves it at default). 

Does this matter? I could just change the prof side to display the students latest preference for each course in a similar manner. Both solutions may add clutter to the prof side of getting a whole bunch of auto filled preferences. Let me know

**Comment by kukuminer** [comment]
I can look into making a "copy previous" button, that seems like a solid idea. It should be possible since I kind of already have the code checking if it needs to re-render the new values. 
Thinking about it, it might make sense to actually just leave the "copy forward" button there permanently, in case the applicant changes their mind. I'll add a disclaimer that it will overwrite their existing preferences.
